
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 93
#define YY_END_OF_BUFFER 94
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[267] =
    {   0,
       85,   85,   94,   92,    1,    2,   57,   92,   47,   59,
       52,   38,   39,   53,   54,   42,   55,   48,   58,   92,
       85,   43,   45,   62,   44,   63,   72,   35,   35,   35,
       36,   37,   68,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   40,   69,
       41,   56,   67,    0,   90,    0,    0,   83,   75,   70,
       80,   73,   50,   76,   51,   89,   77,   49,    0,   84,
        0,   74,   84,   87,    0,    0,    0,    0,   85,   85,
       85,   85,   60,   64,   66,   65,   61,   35,    0,   81,
       35,   35,   35,   35,   35,   35,   30,   35,   35,   35,

       35,   35,   35,   35,   31,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   82,   71,   90,    0,
        0,    0,    0,    0,   89,   89,   46,   84,   84,    0,
       84,   87,   87,    0,   84,   86,   88,   85,   85,   78,
       79,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   24,   35,   35,    5,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,    0,    0,    0,   89,   84,   86,   86,   88,    3,
       35,   11,   15,   35,   35,   35,   35,    8,   12,   35,
       35,   28,    9,   35,   35,   35,   35,   35,   35,   35,

       35,   35,   35,   35,   26,   35,   35,    0,    0,    7,
       19,   35,   35,   35,   35,   20,   35,   35,   21,   35,
       35,   35,   35,   35,   35,   18,   35,   35,   33,    0,
        0,    0,   35,   35,    4,   16,   35,   17,   25,   34,
       32,    6,   10,   35,   35,   35,   91,    0,   35,   27,
       35,   14,   35,   35,    0,    0,    0,    0,   23,   13,
       22,   29,    0,    0,    0,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   24,   26,   26,   27,   28,   29,
       30,   31,   32,    1,   33,   34,   33,   33,   35,   36,
       37,   37,   37,   38,   38,   39,   38,   37,   37,   37,
       38,   37,   37,   37,   40,   38,   37,   41,   38,   38,
       42,   43,   44,   45,   38,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   38,   55,   56,   57,   58,
       59,   60,   38,   61,   62,   63,   64,   65,   66,   67,
       68,   69,   70,   71,   72,   73,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[74] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    4,    4,
        4,    4,    4,    4,    4,    4,    1,    1,    1,    1,
        1,    1,    5,    5,    6,    7,    8,    8,    9,    8,
        8,    3,    1,    3,    1,    5,    5,    5,    5,    6,
        7,    8,    8,    8,    8,    9,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    1,
       10,    1,    1
    } ;

static yyconst flex_int16_t yy_base[274] =
    {   0,
        0,    0,  569,  592,  592,  592,  534,   68,   71,  532,
       67,  592,  592,  531,   63,  592,   64,   79,  515,  107,
      162,  592,  592,   52,  507,   61,  592,    0,    0,  530,
      491,  592,  504,  469,  471,   60,   57,   54,   58,  472,
       83,  471,  479,   84,  456,  465,  463,  468,  592,   49,
      592,  592,  592,  103,  592,  228,  139,  592,  592,  592,
      592,  592,  592,  592,  592,  220,  592,  592,  503,  154,
      242,  592,  277,  136,  178,  315,    0,  475,    0,   79,
       83,   97,  479,  592,  592,  592,  478,    0,  109,  592,
      444,  456,  443,  458,  444,  450,  436,  437,  434,  434,

      437,  433,  430,  469,    0,  428,  430,   92,  428,  104,
       79,  432,  417,  118,   89,  422,  592,  592,  165,  188,
      336,    0,  374,  343,  362,  159,  592,  234,  592,  407,
      439,  592,  198,  351,  398,  216,  592,  160,  592,  592,
      592,  414,  426,  421,  409,  104,  422,  420,  406,  398,
      403,  406,    0,  392,    0,    0,  398,  394,  383,  385,
      387,  394,  380,  377,  377,  389,  379,  382,  386,  373,
      360,  460,  492,  409,  592,    0,  592,  255,  592,    0,
      359,    0,    0,  350,  358,  347,  350,    0,    0,  344,
      341,    0,    0,  341,  341,  329,  341,  331,  335,  330,

      306,  304,  294,  299,    0,  287,  299,  215,  272,    0,
        0,  288,  289,  294,  285,    0,  269,  272,    0,  276,
      273,  275,  259,  264,  264,    0,  252,  250,    0,  275,
      166,  285,  193,  169,    0,    0,  177,    0,    0,    0,
        0,    0,    0,  168,  167,  158,  592,  286,  161,    0,
      148,    0,  147,  141,  220,  226,  232,  186,    0,    0,
        0,    0,  261,  297,   60,  592,  543,  550,  556,  564,
      567,  571,  581
    } ;

static yyconst flex_int16_t yy_def[274] =
    {   0,
      266,    1,  266,  266,  266,  266,  266,  267,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  268,  268,  268,
      266,  266,  266,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  266,  266,
      266,  266,  266,  267,  266,  267,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  269,
      266,  266,  266,   20,  270,  266,  271,  266,   21,  266,
      266,  266,  266,  266,  266,  266,  266,  268,  267,  266,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,

      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  266,  266,  267,  267,
      267,   56,  267,  266,  266,  266,  266,  269,  266,  266,
      266,  266,  266,  266,  272,  271,  266,  266,  266,  266,
      266,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  267,  123,  266,  266,  131,  266,  266,  266,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,

      268,  268,  268,  268,  268,  268,  268,  267,  273,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  273,
      266,  273,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  266,  266,  268,  268,
      268,  268,  268,  268,  266,  266,  266,  266,  268,  268,
      268,  268,  266,  266,  266,    0,  266,  266,  266,  266,
      266,  266,  266
    } ;

static yyconst flex_int16_t yy_nxt[666] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,    4,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   28,   28,   28,   29,   30,   28,
       28,   31,    4,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   29,   41,   29,   42,   29,   29,   29,   29,
       43,   44,   45,   46,   47,   48,   29,   29,   29,   49,
       50,   51,   52,   55,   57,   60,   63,   58,  117,   65,
       83,   84,  258,   66,   66,   66,   66,   66,   66,   66,
       86,   87,   64,   67,   68,   69,   61,   70,   70,   70,

       70,   70,   70,   70,   70,   93,   96,  104,   55,   98,
       56,   99,   94,  101,   55,   97,  102,  137,   95,  118,
      100,  138,   71,   73,  163,   74,   74,   74,   74,   74,
       74,   74,   75,  105,  137,  139,  109,  110,  138,  164,
      106,   76,  169,  158,  170,   56,  111,   77,   78,  112,
       71,   56,  139,  139,  159,  161,   76,  124,  124,  124,
      124,  124,  124,  124,  124,  184,  185,  139,  247,  248,
       55,  167,  162,   77,  132,  133,  266,   77,   73,  168,
       79,   79,   79,   79,   79,   79,   79,   79,  247,  129,
      262,  132,  129,   55,   73,  261,   76,  175,  179,  133,

       80,   81,  266,   78,  129,   71,  133,   56,  260,  129,
      259,   76,   76,  254,  175,  179,  253,   80,  252,   78,
       55,   71,  247,  263,  129,   81,  251,   76,  247,  264,
       56,  250,   82,  119,  247,  265,  132,  120,  125,  125,
      125,  125,  125,  125,  125,  125,  121,  121,  121,  121,
      121,  121,  121,  132,  177,  178,  249,   56,  126,  120,
      130,  130,  130,  130,  130,  130,  130,  130,  132,  129,
      122,  177,  129,  120,  120,  126,   76,  231,  120,  178,
      231,  256,  257,  258,  129,  120,  178,  266,  120,  129,
      120,   76,  120,  177,  123,  131,  131,  131,  131,  131,

      131,  131,  131,  246,  129,  255,  256,  257,  258,  245,
      177,   76,  129,  244,  232,  129,  243,  232,  257,  258,
       71,  242,  241,  240,  239,  177,   76,  129,  134,  238,
      134,  237,  129,  135,  135,  135,  135,  135,  135,  135,
      135,   55,  236,  235,  234,  233,  174,  129,  229,  228,
      227,  226,  225,  224,  172,  172,  172,  172,  172,  172,
      172,  124,  124,  124,  124,  124,  124,  124,  124,  135,
      135,  135,  135,  135,  135,  135,  135,  223,   56,   55,
      125,  125,  125,  125,  125,  125,  125,  125,  222,  221,
      220,  219,  173,  173,  173,  173,  173,  173,  173,  173,

      126,  218,  217,  216,  215,  214,  173,  173,  173,  173,
      213,  212,  211,  210,  209,  207,   56,  126,  206,  173,
      173,  173,  173,  173,  173,  130,  130,  130,  130,  130,
      130,  130,  130,  129,  205,  204,  129,  203,  202,  201,
      200,   76,  199,  198,  197,  196,  195,  194,  129,  193,
      192,  191,  190,  129,  189,  188,   76,  176,  176,  176,
      176,  176,  176,  176,  176,   55,  187,  186,  129,  183,
      182,  181,  180,   76,  129,  171,  166,  129,  208,  208,
      208,  208,  208,  208,  208,  165,  160,  157,   76,  129,
      156,  155,  154,  153,  129,  152,  151,  150,  149,  148,

      147,  146,   56,  145,  144,  143,  142,  141,  140,  129,
      120,  120,  120,  120,  120,  120,  120,  120,   71,  127,
      116,  115,  114,  113,  120,  120,  120,  120,  108,  107,
      103,   92,   91,   90,   71,   89,   85,  120,  120,  120,
      120,  120,  120,   54,   72,   54,   54,   54,   54,   54,
       54,   54,   54,   88,   88,   88,   88,   88,   88,  128,
       62,   59,  128,   53,  128,  128,   75,   75,  266,   75,
      136,  136,  136,  136,  135,  266,  266,  135,  266,  135,
      135,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,    3,  266,  266,  266,  266,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266
    } ;

static yyconst flex_int16_t yy_chk[666] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    8,    9,   11,   15,    9,   50,   17,
       24,   24,  265,   17,   17,   17,   17,   17,   17,   17,
       26,   26,   15,   17,   17,   18,   11,   18,   18,   18,

       18,   18,   18,   18,   18,   36,   37,   41,   54,   38,
        8,   38,   36,   39,   89,   37,   39,   80,   36,   50,
       38,   81,   18,   20,  111,   20,   20,   20,   20,   20,
       20,   20,   20,   41,   80,   82,   44,   44,   81,  111,
       41,   20,  115,  108,  115,   54,   44,   20,   20,   44,
       20,   89,   82,   81,  108,  110,   20,   57,   57,   57,
       57,   57,   57,   57,   57,  146,  146,   82,  231,  231,
      119,  114,  110,   20,   74,   74,   74,   20,   21,  114,
       21,   21,   21,   21,   21,   21,   21,   21,  258,   70,
      254,   74,   70,  120,   75,  253,   21,  126,  138,   74,

       21,   21,   74,   21,   70,   21,   74,  119,  251,   70,
      249,   21,   75,  246,  126,  138,  245,   21,  244,   75,
      208,   75,  255,  255,   70,   21,  237,   75,  256,  256,
      120,  234,   21,   56,  257,  257,  133,   56,   66,   66,
       66,   66,   66,   66,   66,   66,   56,   56,   56,   56,
       56,   56,   56,  133,  136,  136,  233,  208,   66,   56,
       71,   71,   71,   71,   71,   71,   71,   71,  133,  128,
       56,  136,  128,   56,   56,   66,   71,  209,   56,  136,
      230,  263,  263,  263,  128,   56,  136,  232,   56,  128,
       56,   71,   56,  178,   56,   73,   73,   73,   73,   73,

       73,   73,   73,  228,  128,  248,  248,  248,  248,  227,
      178,   73,   73,  225,  209,   73,  224,  230,  264,  264,
       73,  223,  222,  221,  220,  178,   73,   73,   76,  218,
       76,  217,   73,   76,   76,   76,   76,   76,   76,   76,
       76,  121,  215,  214,  213,  212,  124,   73,  207,  206,
      204,  203,  202,  201,  121,  121,  121,  121,  121,  121,
      121,  124,  124,  124,  124,  124,  124,  124,  124,  134,
      134,  134,  134,  134,  134,  134,  134,  200,  121,  123,
      125,  125,  125,  125,  125,  125,  125,  125,  199,  198,
      197,  196,  123,  123,  123,  123,  123,  123,  123,  123,

      125,  195,  194,  191,  190,  187,  123,  123,  123,  123,
      186,  185,  184,  181,  174,  171,  123,  125,  170,  123,
      123,  123,  123,  123,  123,  130,  130,  130,  130,  130,
      130,  130,  130,  135,  169,  168,  135,  167,  166,  165,
      164,  130,  163,  162,  161,  160,  159,  158,  135,  157,
      154,  152,  151,  135,  150,  149,  130,  131,  131,  131,
      131,  131,  131,  131,  131,  172,  148,  147,  135,  145,
      144,  143,  142,  131,  131,  116,  113,  131,  172,  172,
      172,  172,  172,  172,  172,  112,  109,  107,  131,  131,
      106,  104,  103,  102,  131,  101,  100,   99,   98,   97,

       96,   95,  172,   94,   93,   92,   91,   87,   83,  131,
      173,  173,  173,  173,  173,  173,  173,  173,   78,   69,
       48,   47,   46,   45,  173,  173,  173,  173,   43,   42,
       40,   35,   34,   33,   31,   30,   25,  173,  173,  173,
      173,  173,  173,  267,   19,  267,  267,  267,  267,  267,
      267,  267,  267,  268,  268,  268,  268,  268,  268,  269,
       14,   10,  269,    7,  269,  269,  270,  270,    3,  270,
      271,  271,  271,  271,  272,    0,    0,  272,    0,  272,
      272,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  266,  266,  266,  266,  266,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "exp.lex"
#line 3 "exp.lex"
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include "exp.h"
#include "y.tab.h"

extern "C" int yylex();

/* Lexical Elements taken from "The C89 Draft" - http://port70.net/~nsz/c/c89/c89-draft.html */
/* Keyword List */
/* End of Keyword List */
/* Operator sizeof */
/* Identifiers */
/* Punctuator List */
/* Operator List */
/* Constants */
/*CONSTENUM*/
/* Misc */
#line 717 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 127 "exp.lex"


#line 907 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 267 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 592 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 129 "exp.lex"

	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 130 "exp.lex"
return NEWLINE;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 132 "exp.lex"
return TAuto;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 133 "exp.lex"
return TDouble;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 134 "exp.lex"
return TInt;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 135 "exp.lex"
return TStruct;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 136 "exp.lex"
return TBreak;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 137 "exp.lex"
return TElse;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 138 "exp.lex"
return TLong;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 139 "exp.lex"
return TSwitch;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 140 "exp.lex"
return TCase;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 141 "exp.lex"
return TEnum;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 142 "exp.lex"
return TRegister;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 143 "exp.lex"
return TTypedef;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 144 "exp.lex"
return TChar;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 145 "exp.lex"
return TExtern;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 146 "exp.lex"
return TReturn;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 147 "exp.lex"
return TUnion;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 148 "exp.lex"
return TConst;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 149 "exp.lex"
return TFloat;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 150 "exp.lex"
return TShort;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 151 "exp.lex"
return TUnsigned;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 152 "exp.lex"
return TContinue;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 153 "exp.lex"
return TFor;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 154 "exp.lex"
return TSigned;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 155 "exp.lex"
return TVoid;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 156 "exp.lex"
return TDefault;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 157 "exp.lex"
return TGoto;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 158 "exp.lex"
return TVolatile;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 159 "exp.lex"
return TDo;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 160 "exp.lex"
return TIf;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 161 "exp.lex"
return TStatic;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 162 "exp.lex"
return TWhile;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 163 "exp.lex"
return TSizeof;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 165 "exp.lex"
yylval.id = strdup(yytext); return TIdentifier;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 167 "exp.lex"
return TOpenBracket;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 168 "exp.lex"
return TCloseBracket;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 169 "exp.lex"
return TOpenRound;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 170 "exp.lex"
return TCloseRound;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 171 "exp.lex"
return TOpenBrace;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 172 "exp.lex"
return TCloseBrace;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 173 "exp.lex"
return TComma;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 174 "exp.lex"
return TColon;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 175 "exp.lex"
return TEqual;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 176 "exp.lex"
return TSemicolon;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 178 "exp.lex"
return TEllipsis;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 179 "exp.lex"
return THash;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 180 "exp.lex"
return TPeriod;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 181 "exp.lex"
return TArrow;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 182 "exp.lex"
return TIncrement;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 183 "exp.lex"
return TDecrement;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 184 "exp.lex"
return TBitwiseAnd;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 185 "exp.lex"
return TAsterisk;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 186 "exp.lex"
return TAdd;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 187 "exp.lex"
return TSubtract;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 188 "exp.lex"
return TBitwiseNot;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 189 "exp.lex"
return TLogicNot;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 190 "exp.lex"
return TDivide;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 191 "exp.lex"
return TModulo;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 192 "exp.lex"
return TLeftShift;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 193 "exp.lex"
return TRightShift;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 194 "exp.lex"
return TLessThan;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 195 "exp.lex"
return TGreaterThan;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 196 "exp.lex"
return TLessEqual;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 197 "exp.lex"
return TGreaterEqual;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 198 "exp.lex"
return TLogicEqual;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 199 "exp.lex"
return TNotEqual;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 200 "exp.lex"
return THat;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 201 "exp.lex"
return TBitwiseOr;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 202 "exp.lex"
return TAnd;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 203 "exp.lex"
return TOr;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 204 "exp.lex"
return TQuestion;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 205 "exp.lex"
return TMultEqual;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 206 "exp.lex"
return TDivEqual;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 207 "exp.lex"
return TModEqual;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 208 "exp.lex"
return TAddEqual;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 209 "exp.lex"
return TSubEqual;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 210 "exp.lex"
return TLeftShiftEqual;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 211 "exp.lex"
return TRightShiftEqual;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 212 "exp.lex"
return TAndEqual;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 213 "exp.lex"
return THatEqual;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 214 "exp.lex"
return TOrEqual;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 215 "exp.lex"
return TDoubleHash;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 217 "exp.lex"
return TConstFloat;  
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 218 "exp.lex"
yylval.num = atoi(yytext); return TConstInt;    
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 219 "exp.lex"
return THexInt;      
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 220 "exp.lex"
return TOctalInt;    
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 221 "exp.lex"
yylval.num = atoi(yytext); return TUnsignedInt; 
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 222 "exp.lex"
yylval.num = atoi(yytext); return TSignedInt;   
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 224 "exp.lex"
yylval.id = strdup(yytext); return TStringLiteral;
	YY_BREAK
case 91:
/* rule 91 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 226 "exp.lex"

	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 228 "exp.lex"

	YY_BREAK
case 93:
YY_RULE_SETUP
#line 230 "exp.lex"
ECHO;
	YY_BREAK
#line 1461 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 267 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 267 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 266);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 230 "exp.lex"





